
import { Enum } from 'enumify';

export default class TimerActions extends Enum {}
TimerActions.initEnum([
  'GET_TIMERS_REQUEST',
  'GET_TIMERS_RESPONSE',
  'GET_TIMERS_ERROR',
  'GET_TIMER_REQUEST',
  'GET_TIMER_RESPONSE',
  'GET_TIMER_ERROR',
  'SAVE_TIMER_REQUEST',
  'SAVE_TIMER_RESPONSE',
  'SAVE_TIMER_ERROR',
  'GET_TIMER_LOGS_REQUEST',
  'GET_TIMER_LOGS_RESPONSE',
  'GET_TIMER_LOGS_ERROR',
  'START_TIMER_REQUEST',
  'START_TIMER_RESPONSE',
  'START_TIMER_ERROR',
  'STOP_TIMER_REQUEST',
  'STOP_TIMER_RESPONSE',
  'STOP_TIMER_ERROR',
]);
